# Build Config
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.6-browsers
    working_directory: ~/swingessentialsweb
    environment:
      - MASTER_BRANCH: master
      - DEV_BRANCH: dev
      - GH_EMAIL: boyle.p.joseph@gmail.com
      - GH_NAME: joebochill
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: 
          name: Install Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # Run Tests
      # - run: 
      #     name: Run Tests
      #     command: yarn test
      
      # Build
      - run: 
          name: Build
          command: yarn build
      
      # Deploy to web
      - deploy:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH == $MASTER_BRANCH ]; then

            fi 
            if [ $CIRCLE_BRANCH == $DEV_BRANCH ]; then
              yarn deploy
            fi 